routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('daily', 'DashboardsController@getDaily')->name('daily');

Route::get('regional', 'DashboardsController@getRegional')->name('regional');

Route::get('region', 'DashboardsController@getRegion')->name('region');

// Route::get('group', 'DashboardsController@getGroup')->name('group');

// Route::get('families', 'DashboardsController@getFamily')->name('families');

// Route::get('corporate', 'DashboardsController@getCorporate')->name('corporate');

// Route::get('safari', 'DashboardsController@getSafari')->name('safari');

Route::get('individual', 'DashboardsController@getIndividual')->name('individual');

Route::get('/', 'Auth\AdminLoginController@getIndex');

// Search Subscribers
Route::post('search', 'SearchController@index')->name('search');

// Administrator Management
Route::resource('administrators', 'AdministratorsController');

// Subscriber Management
Route::resource('subscribers', 'SubscribersController');

// Packages Management
Route::resource('packages', 'PackagesController');

// Group Type Management
// Route::resource('group_types', 'Group_typesController');

// Question Bank Management
Route::resource('questions', 'QuestionsController');

// Family Management
Route::resource('family', 'FamilyController');

// Corporate Management
Route::resource('corporate', 'CorporateController');

// Corporate Management
Route::resource('safari', 'SafariController');

// Groups Management
// Route::resource('groups', 'GroupsController');

// Comments
Route::post('comment/{id}', ['uses' => 'CommentController@store', 'as' => 'comment.store']);
Route::put('comment/{id}', ['uses' => 'CommentController@update', 'as' => 'comment.update']);
Route::delete('comment/{id}', ['uses' => 'CommentController@destroy', 'as' => 'comment.destroy']);
// ========

// Group Comments
// Route::post('comment_groups/{group_id}', ['uses' => 'Comment_groupsController@store', 'as' => 'comment_group.store']);
// Route::put('comment_groups/{comment_id}', ['uses' => 'Comment_groupsController@update', 'as' => 'comment_group.update']);
// ========

// Payments
Route::get('payment/{id}', ['uses' => 'PaymentController@index', 'as' => 'payment.index']); // the id here is the id of the subscriber, family, corporate, safari
Route::post('payment/{id}', ['uses' => 'PaymentController@store', 'as' => 'payment.store']); // the id here is the id of the subscriber, family, corporate, safari
Route::put('payment/{payment_id}/{maker}/{id}', ['uses' => 'PaymentController@update', 'as' => 'payment.update']); // the 'maker' is the whoever is making the payment
Route::delete('payment/{payment_id}/{maker}/{id}', ['uses' => 'PaymentController@destroy', 'as' => 'payment.destroy']);
// ========

// Admin Login
Route::prefix('admin')->group(function() {
	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
	// Route::get('/', 'AdminController@index')->name('admin.dashboard');
	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

	// Password reset routes
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
});
// =========

resources/views/partials/_footer.blade.php
<footer class="text-muted bg-light fixed-bottom">
  <div class="container">
    <p class="float-right m-0">
      <a href="#"><i class="fas fa-arrow-up"></i></a>
    </p>
    <p class="m-0">The Remote Rescue Plan is trademarked by <a href src="#">ACE Air & Ambulance (Pvt) Ltd</a></p>
    <!-- <p>New to this Remote Rescue Subscription tool? <a href="../../">Visit the User tutorial page</a>.</p> -->
  </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

@yield('scripts')

resources/views/partials/_head.blade.php
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Page Specific CSS -->
  @yield('stylesheets')

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <!-- Fontawesome CSS -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  <!-- Custom CSS -->
  <link href="{{ asset('css/custom.css') }}" rel="stylesheet" type="text/css">

  <title>RR @yield('title')</title>
</head>

resources/views/partials/_messages.blade.php
<div class="row">
  <div class="col-md-8 offset-md-2">

    @if (Session::has('success'))

      <div class="alert alert-message alert-success alert-dismissible" role="alert">
        <strong>Success:</strong> {{ Session::get('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    @endif

    @if (count($errors))

      <div class="alert alert-message alert-danger alert-dismissible" role="alert">
        <strong>Error(s):</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>

    @endif

  </div>
</div>

resources/views/partials/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{{ route('individual') }}">Remote Rescue</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      @if(Auth::check())
      <ul class="navbar-nav mr-auto">
          @if(Auth::user()->role_id < 3)
        <li class="nav-item dropdown {{ Request::is('subscribers/create', 'groups/create') ? 'active' : '' }}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('subscribers.create') }}">Subscriber</a>
            <a class="dropdown-item" href="{{ route('family.create') }}">Family</a>
            <a class="dropdown-item" href="{{ route('corporate.create') }}">Corporate</a>
            <a class="dropdown-item" href="{{ route('safari.create') }}">Safari Camp</a>
          </div>
        </li>
        @endif
        <li class="nav-item {{ Request::is('individual', 'family', 'corporate', 'safari', 'region', 'regional') ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('individual') }}">Dashboards</a>
        </li>
      </ul>

      <form action="{{ url('/search') }}" method="POST" class="input-group search-bar-group my-2 my-lg-0">
          {{ csrf_field() }}
        <input class="form-control search-bar" name="search" placeholder="Search Subscribers by name">
        <div class="input-group-append">
          <button class="btn btn-search-bar" type="submit" id="button-addon2"><i class="fas fa-search"></i></button>
        </div>
      </form>

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ Auth::user()->first }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('administrators.show', Auth::user()->id) }}">Profile</a>
            <a class="dropdown-item" href="{{ route('admin.logout') }}">Logout</a>
          </div>
        </li>

        <li class="nav-item dropdown {{ Request::is('questions', 'packages', 'group_types') ? 'active' : '' }}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-cog"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('questions.index') }}">Questions</a>
            <a class="dropdown-item" href="{{ route('packages.index') }}">Packages</a>
            {{-- <a class="dropdown-item" href="{{ route('group_types.index') }}">Group Types</a> --}}

            @if(Auth::user()->role_id == 1)
            <a class="dropdown-item bg-danger text-light" href="{{ route('administrators.index') }}">Administrators</a>
            @endif
            
          </div>
        </li>        
      </ul>
      @endif
    </div>
  </div>
</nav>

resources/views/partials/_sidemenu.blade.php
<div class="list-group list-group-flush">
	<a href="{{ route('individual') }}" class="list-group-item list-group-item-action {{ Request::is('individual') ? 'active' : '' }}">Individuals</a>
	{{-- <a href="{{ route('group') }}" class="list-group-item list-group-item-action ">Groups</a> --}}
  <a href="{{ route('family.index') }}" class="list-group-item list-group-item-action {{ Request::is('family') ? 'active' : '' }}">Family</a>
  <a href="{{ route('corporate.index') }}" class="list-group-item list-group-item-action {{ Request::is('corporate') ? 'active' : '' }}">Corporate</a>
  <a href="{{ route('safari.index') }}" class="list-group-item list-group-item-action {{ Request::is('safari') ? 'active' : '' }}">Safari Camps</a>
  <a href="{{ route('region') }}" class="list-group-item list-group-item-action {{ Request::is('region') ? 'active' : '' }}">Regional</a>
	<a href="{{ route('regional') }}" class="list-group-item list-group-item-action {{ Request::is('regional') ? 'active' : '' }}">Regional+</a>
	<a href="{{ route('daily') }}" class="list-group-item list-group-item-action {{ Request::is('daily') ? 'active' : '' }}">Daily</a>
</div>

{{-- <div class="accordion side-menu pb-5" id="accordionExample">

	<div class="card">
	  <div class="card-header {{ Request::is('individual') ? 'active' : '' }}" id="headingOne">
		  <a href="{{ route('individual') }}" class="btn btn-link p-0 {{ Request::is('individual') ? 'active' : '' }}">Individuals</a>
	  </div>
  </div>
  
	<div class="card">
	  <div class="card-header d-flex justify-content-between align-items-center {{ Request::is('family', 'corporate', 'safari') ? 'active' : '' }}" id="headingTwo">
      <button class="btn btn-link p-0 collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Groups
      </button>
      <i class="fas fa-caret-down" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"></i>
	  </div>
	  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body p-0">
        <div class="list-group list-group-flush side-menu-drop">
          <a href="{{ route('family') }}" class="list-group-item list-group-item-action {{ Request::is('family') ? 'active' : '' }}">Family</a>
          <a href="{{ route('corporate') }}" class="list-group-item list-group-item-action {{ Request::is('corporate') ? 'active' : '' }}">Corporate</a>
          <a href="{{ route('safari') }}" class="list-group-item list-group-item-action {{ Request::is('safari') ? 'active' : '' }}">Safari Camps</a>
        </div>
      </div>
	  </div>
  </div>
  
	<div class="card">
    <div class="card-header {{ Request::is('region') ? 'active' : '' }}" id="headingThree">
      <a href="{{ route('region') }}" class="btn btn-link p-0 {{ Request::is('region') ? 'active' : '' }}">Regional</a>
    </div>
  </div>

  <div class="card">
    <div class="card-header {{ Request::is('regional') ? 'active' : '' }}" id="headingFour">
      <a href="{{ route('regional') }}" class="btn btn-link p-0 {{ Request::is('regional') ? 'active' : '' }}">Regional Ex</a>
    </div>
  </div>
  
  <div class="card">
    <div class="card-header {{ Request::is('daily') ? 'active' : '' }}" id="headingFive">
      <a href="{{ route('daily') }}" class="btn btn-link p-0 {{ Request::is('daily') ? 'active' : '' }}">Daily</a>
    </div>
  </div>
</div> --}}