routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('daily', 'DashboardsController@getDaily')->name('daily');

Route::get('regional', 'DashboardsController@getRegional')->name('regional');

Route::get('region', 'DashboardsController@getRegion')->name('region');

// Route::get('group', 'DashboardsController@getGroup')->name('group');

// Route::get('families', 'DashboardsController@getFamily')->name('families');

// Route::get('corporate', 'DashboardsController@getCorporate')->name('corporate');

// Route::get('safari', 'DashboardsController@getSafari')->name('safari');

Route::get('individual', 'DashboardsController@getIndividual')->name('individual');

Route::get('/', 'Auth\AdminLoginController@getIndex');

// Search Subscribers
Route::post('search', 'SearchController@index')->name('search');

// Administrator Management
Route::resource('administrators', 'AdministratorsController');

// Subscriber Management
Route::resource('subscribers', 'SubscribersController');

// Packages Management
Route::resource('packages', 'PackagesController');

// Group Type Management
// Route::resource('group_types', 'Group_typesController');

// Question Bank Management
Route::resource('questions', 'QuestionsController');

// Family Management
Route::resource('family', 'FamilyController');

// Corporate Management
Route::resource('corporate', 'CorporateController');

// Corporate Management
Route::resource('safari', 'SafariController');

// Groups Management
// Route::resource('groups', 'GroupsController');

// Comments
Route::post('comment/{id}', ['uses' => 'CommentController@store', 'as' => 'comment.store']);
Route::put('comment/{id}', ['uses' => 'CommentController@update', 'as' => 'comment.update']);
Route::delete('comment/{id}', ['uses' => 'CommentController@destroy', 'as' => 'comment.destroy']);
// ========

// Group Comments
// Route::post('comment_groups/{group_id}', ['uses' => 'Comment_groupsController@store', 'as' => 'comment_group.store']);
// Route::put('comment_groups/{comment_id}', ['uses' => 'Comment_groupsController@update', 'as' => 'comment_group.update']);
// ========

// Payments
Route::get('payment/{id}', ['uses' => 'PaymentController@index', 'as' => 'payment.index']); // the id here is the id of the subscriber, family, corporate, safari
Route::post('payment/{id}', ['uses' => 'PaymentController@store', 'as' => 'payment.store']); // the id here is the id of the subscriber, family, corporate, safari
Route::put('payment/{payment_id}/{maker}/{id}', ['uses' => 'PaymentController@update', 'as' => 'payment.update']); // the 'maker' is the whoever is making the payment
Route::delete('payment/{payment_id}/{maker}/{id}', ['uses' => 'PaymentController@destroy', 'as' => 'payment.destroy']);
// ========

// Admin Login
Route::prefix('admin')->group(function() {
	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
	// Route::get('/', 'AdminController@index')->name('admin.dashboard');
	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

	// Password reset routes
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
});
// =========

app/Http/Controllers/DashboardsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Session;

use App\Subscriber;
use App\Group;
use App\Payment;
use App\Group_type;
use App\Family;

class DashboardsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function getIndividual()
    {
        $subscribers = Subscriber::all()->where('package_id', '=', '1');
        $payments = Payment::all();

        $count = $subscribers->count();
        $processing = $subscribers->where('vetting', '<', '0')->count();
        $fail = $subscribers->where('vetting', '=', '0')->count();

        return view('dashboards.individual')
            ->withSubscribers($subscribers)
            ->withCount($count)
            ->withProcessing($processing)
            ->withFail($fail);
    }

    public function getRegion()
    {
        $subscribers = Subscriber::all()->where('package_id', '=', '3');

        $count = $subscribers->count();
        $processing = $subscribers->where('vetting', '<', '0')->count();
        $fail = $subscribers->where('vetting', '=', '0')->count();

        return view('dashboards.region')
            ->withSubscribers($subscribers)
            ->withCount($count)
            ->withProcessing($processing)
            ->withFail($fail);
    }

    public function getRegional()
    {
        $subscribers = Subscriber::all()->where('package_id', '=', '4');

        $count = $subscribers->count();
        $processing = $subscribers->where('vetting', '<', '0')->count();
        $fail = $subscribers->where('vetting', '=', '0')->count();

        return view('dashboards.regional')
            ->withSubscribers($subscribers)
            ->withCount($count)
            ->withProcessing($processing)
            ->withFail($fail);
    }

    public function getDaily()
    {
        $subscribers = Subscriber::all()->where('package_id', '=', '5');

        $count = $subscribers->count();
        $processing = $subscribers->where('vetting', '<', '0')->count();
        $fail = $subscribers->where('vetting', '=', '0')->count();

        return view('dashboards.daily')
            ->withSubscribers($subscribers)
            ->withCount($count)
            ->withProcessing($processing)
            ->withFail($fail);
    }
}

resources/views/dashboards/corporate.blade.php
@extends('main')

@section('title', '| Group')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <div class="d-flex justify-content-between align-items-baseline">
      <h2 class="mr-2">Corporate</h2>
      <h4>Group</h4>
    </div>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Groups
        </span>
      </div>
      {{-- <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-warning mr-2">40 Due</span>
        <span class="badge badge-pill badge-danger mr-2">40 Over Due</span>
      </div> --}}
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Group Name</th>
            <th scope="col">Group#</th>
            <th scope="col">Members</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($groups as $group)
          <tr class="">
            <td>{{ $group->group_name }}</td>
            <td class="">{{ Helper::rr_group_id( $group->id) }}</td>
            <td>{{ $group->group_type->title }}</td>
            <td>
              <div class="btn-toolbar justify-content-end">
                <a href="{{ route('groups.show', $group->id) }}" class="btn btn-outline-dark btn-xs mr-2">View</a>
                <a href="{{ route('groups.edit', $group->id) }}" class="btn btn-outline-dark btn-xs">Edit</a>
              </div>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
  </div>
</div>

@stop

resources/views/dashboards/daily.blade.php
@extends('main')

@section('title', '| Daily')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <h2 class="dashboard-title">Daily</h2>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Subscribers
        </span>
      </div>
      <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-info mr-2">{{ $processing }} Processing</span>
        <span class="badge badge-pill badge-dark">{{ $fail }} Fail</span>
      </div>
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Name</th>
            <th scope="col">Account#</th>
            <th scope="col">Vetting</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($subscribers as $subscriber)
          <tr>

            @if(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->start_date))))->diff(new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->format('%m') == 1)
            <td class="text-dark"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) > 30)
            <td class="text-primary"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) < 0)
            <td class="text-danger"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->diff(new DateTime(date('Y-m-d', strtotime(time()))))->format('%d') < 31)
            <td class="text-warning"><i class="fas fa-circle"></i></td>
            @else
            <td><i class="far fa-circle"></i></td>
            @endif

            <td class="">{{ $subscriber->first }} {{ $subscriber->last }}</td>
            <td class="">{{ Helper::rr_subscriber_id( $subscriber->id) }}</td>
            
            @if($subscriber->vetting > 0)
            <td class="text-success"><i class="fas fa-check-circle"></i></td>
            @elseif($subscriber->vetting < 0)
            <td class="text-info"><i class="fas fa-tasks"></i></td>
            @elseif($subscriber->vetting == 0)
            <td class="text-danger"><i class="fas fa-times-circle"></i></td>
            @endif
            
            <td>
              <a href="{{ route('subscribers.show', $subscriber->id) }}" class=""><i class="fas fa-arrow-right"></i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@stop

resources/views/dashboards/family.blade.php
@extends('main')

@section('title', '| Group')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <div class="d-flex justify-content-between align-items-baseline">
      <h2 class="mr-2">Family</h2>
      <h4>Group</h4>
    </div>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Families
        </span>
      </div>
      {{-- <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-warning mr-2">40 Due</span>
        <span class="badge badge-pill badge-danger mr-2">40 Over Due</span>
      </div> --}}
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Group Name</th>
            <th scope="col">Group#</th>
            <th scope="col">Dependants</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($families as $family)
          <tr>
            <td>{{ $family->name }}</td>
            <td>{{ Helper::rr_group_id($family->group_id) }}</td>
            <td>{{ $family->dependants }}</td>
            <td>
              <div class="btn-toolbar justify-content-end">
                <a href="{{ route('family.show', $family->id) }}" class="btn btn-outline-dark btn-xs mr-2">View</a>
                <a href="{{ route('family.edit', $family->id) }}" class="btn btn-outline-dark btn-xs">Edit</a>
              </div>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
  </div>
</div>

@stop

resources/views/dashboards/group.blade.php
@extends('main')

@section('title', '| Group')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <h2 class="mr-2">Groups</h2>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Groups
        </span>
      </div>
      {{-- <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-warning mr-2">40 Due</span>
        <span class="badge badge-pill badge-danger mr-2">40 Over Due</span>
      </div> --}}
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Group Name</th>
            <th scope="col">Group#</th>
            <th scope="col">Group Type</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($groups as $group)
          <tr class="">
            <td>{{ $group->group_name }}</td>
            <td class="">{{ Helper::rr_group_id( $group->id) }}</td>
            <td>{{ $group->group_type->title }}</td>
            <td>
              <div class="btn-toolbar justify-content-end">
                <a href="{{ route('groups.show', $group->id) }}" class="btn btn-outline-dark btn-xs mr-2">View</a>
                <a href="{{ route('groups.edit', $group->id) }}" class="btn btn-outline-dark btn-xs">Edit</a>
              </div>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
    <h2 class="mr-2">Group Members</h2>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count_subscribers }} Subscribers
        </span>
      </div>
      <div class="d-flex align-items-center badges-stats">
        {{-- <span class="badge badge-pill badge-warning mr-2">{{ $due }} Due</span> --}}
        {{-- <span class="badge badge-pill badge-danger mr-2">{{ $past }} Past</span> --}}
        <span class="badge badge-pill badge-info mr-2">{{ $processing }} Processing</span>
        <span class="badge badge-pill badge-dark">{{ $fail }} Fail</span>
      </div>
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Account#</th>
            <th scope="col">Vetting</th>
            <th class="btn-dashboard"></th>
          </tr>
        </thead>
        <tbody>

          @foreach($subscribers as $subscriber)
          <tr>
            <td class="">{{ $subscriber->first }} {{ $subscriber->last }}</td>
            <td class="">{{ Helper::rr_subscriber_id( $subscriber->id) }}</td>
            @if($subscriber->vetting > 0)
            <td><span class="badge badge-pill badge-success">Pass</span></td>
            @elseif($subscriber->vetting < 0)
            <td><span class="badge badge-pill badge-info">Processing</span></td>
            @elseif($subscriber->vetting == 0)
            <td><span class="badge badge-pill badge-dark">Fail</span></td>
            @endif
            <td class="">
              <div class="btn-toolbar justify-content-end">
                <a href="{{ route('subscribers.show', $subscriber->id) }}" class="btn btn-outline-dark btn-xs mr-2">View</a>
                <a href="{{ route('subscribers.edit', $subscriber->id) }}" class="btn btn-outline-dark btn-xs">Edit</a>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@stop

resources/views/dashboards/individual.blade.php
@extends('main')

@section('title', '| Individual')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <h2 class="dashboard-title">Individuals</h2>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Subscribers
        </span>
      </div>
      <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-info mr-2">{{ $processing }} Processing</span>
        <span class="badge badge-pill badge-dark">{{ $fail }} Fail</span>
      </div>
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Name</th>
            <th scope="col">Account#</th>
            <th scope="col">Vetting</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($subscribers as $subscriber)
          <tr>

            @if(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->start_date))))->diff(new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->format('%m') == 1)
            <td class="text-dark"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) > 30)
            <td class="text-primary"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) < 0)
            <td class="text-danger"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->diff(new DateTime(date('Y-m-d', strtotime(time()))))->format('%d') < 31)
            <td class="text-warning"><i class="fas fa-circle"></i></td>
            @else
            <td><i class="far fa-circle"></i></td>
            @endif

            <td class="">{{ $subscriber->first }} {{ $subscriber->last }}</td>
            <td class="">{{ Helper::rr_subscriber_id( $subscriber->id) }}</td>
            
            @if($subscriber->vetting > 0)
            <td class="text-success"><i class="fas fa-check-circle"></i></td>
            @elseif($subscriber->vetting < 0)
            <td class="text-info"><i class="fas fa-tasks"></i></td>
            @elseif($subscriber->vetting == 0)
            <td class="text-danger"><i class="fas fa-times-circle"></i></td>
            @endif
            
            <td>
              <a href="{{ route('subscribers.show', $subscriber->id) }}" class=""><i class="fas fa-arrow-right"></i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@stop

resources/views/dashboards/region.blade.php
@extends('main')

@section('title', '| Redional')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <h2 class="dashboard-title">Regional</h2>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Subscribers
        </span>
      </div>
      <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-info mr-2">{{ $processing }} Processing</span>
        <span class="badge badge-pill badge-dark">{{ $fail }} Fail</span>
      </div>
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Name</th>
            <th scope="col">Account#</th>
            <th scope="col">Vetting</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($subscribers as $subscriber)
          <tr>

            @if(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->start_date))))->diff(new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->format('%m') == 1)
            <td class="text-dark"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) > 30)
            <td class="text-primary"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) < 0)
            <td class="text-danger"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->diff(new DateTime(date('Y-m-d', strtotime(time()))))->format('%d') < 31)
            <td class="text-warning"><i class="fas fa-circle"></i></td>
            @else
            <td><i class="far fa-circle"></i></td>
            @endif

            <td class="">{{ $subscriber->first }} {{ $subscriber->last }}</td>
            <td class="">{{ Helper::rr_subscriber_id( $subscriber->id) }}</td>
            
            @if($subscriber->vetting > 0)
            <td class="text-success"><i class="fas fa-check-circle"></i></td>
            @elseif($subscriber->vetting < 0)
            <td class="text-info"><i class="fas fa-tasks"></i></td>
            @elseif($subscriber->vetting == 0)
            <td class="text-danger"><i class="fas fa-times-circle"></i></td>
            @endif
            
            <td>
              <a href="{{ route('subscribers.show', $subscriber->id) }}" class=""><i class="fas fa-arrow-right"></i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@stop

resources/views/dashboards/regional.blade.php
@extends('main')

@section('title', '| Regional')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <h2 class="dashboard-title">Regional+</h2>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Subscribers
        </span>
      </div>
      <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-info mr-2">{{ $processing }} Processing</span>
        <span class="badge badge-pill badge-dark">{{ $fail }} Fail</span>
      </div>
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th></th>
            <th scope="col">Name</th>
            <th scope="col">Account#</th>
            <th scope="col">Vetting</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($subscribers as $subscriber)
          <tr>

            @if(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->start_date))))->diff(new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->format('%m') == 1)
            <td class="text-dark"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) > 30)
            <td class="text-primary"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (round(strtotime($subscriber->payments[0]->end_date) - time()) / (60 * 60 * 24)) < 0)
            <td class="text-danger"><i class="fas fa-circle"></i></td>
            @elseif(count($subscriber->payments) > 0 && (new DateTime(date('Y-m-d', strtotime($subscriber->payments[0]->end_date))))->diff(new DateTime(date('Y-m-d', strtotime(time()))))->format('%d') < 31)
            <td class="text-warning"><i class="fas fa-circle"></i></td>
            @else
            <td><i class="far fa-circle"></i></td>
            @endif

            <td class="">{{ $subscriber->first }} {{ $subscriber->last }}</td>
            <td class="">{{ Helper::rr_subscriber_id( $subscriber->id) }}</td>
            
            @if($subscriber->vetting > 0)
            <td class="text-success"><i class="fas fa-check-circle"></i></td>
            @elseif($subscriber->vetting < 0)
            <td class="text-info"><i class="fas fa-tasks"></i></td>
            @elseif($subscriber->vetting == 0)
            <td class="text-danger"><i class="fas fa-times-circle"></i></td>
            @endif
            
            <td>
              <a href="{{ route('subscribers.show', $subscriber->id) }}" class=""><i class="fas fa-arrow-right"></i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@stop

resources/views/dashboards/safari.blade.php
@extends('main')

@section('title', '| Group')

@section('content')

<div class="row pb-80">
  <div class="col-md-3">
    <h2>Packages</h2>
    @include('partials._sidemenu')
  </div>
  <div class="col-md-9">
    <div class="d-flex justify-content-between align-items-baseline">
      <h2 class="mr-2">Safari Camps</h2>
      <h4>Group</h4>
    </div>
    <div class="d-flex justify-content-between flex-wrap mb-2">
      <div class="d-flex align-items-center">
        <span class="badge badge-pill badge-primary">{{ $count }} Groups
        </span>
      </div>
      {{-- <div class="d-flex align-items-center badges-stats">
        <span class="badge badge-pill badge-warning mr-2">40 Due</span>
        <span class="badge badge-pill badge-danger mr-2">40 Over Due</span>
      </div> --}}
    </div>
    <div class="table-responsive-md">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Group Name</th>
            <th scope="col">Group#</th>
            <th scope="col">Members</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          @foreach($groups as $group)
          <tr class="">
            <td>{{ $group->group_name }}</td>
            <td class="">{{ Helper::rr_group_id( $group->id) }}</td>
            <td>{{ $group->group_type->title }}</td>
            <td>
              <div class="btn-toolbar justify-content-end">
                <a href="{{ route('groups.show', $group->id) }}" class="btn btn-outline-dark btn-xs mr-2">View</a>
                <a href="{{ route('groups.edit', $group->id) }}" class="btn btn-outline-dark btn-xs">Edit</a>
              </div>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
  </div>
</div>

@stop